import { KeysEnum } from '@shared/common/keys.enum/keys.enum';
import { ContactDto } from '@app/crm/clients/contact.dto';

export const ClientFields: KeysEnum<ContactDto> = {
    Id: 'Id',
    Name: 'Name',
    CompanyName: 'CompanyName',
    Email: 'Email',
    PhotoPublicId: 'PhotoPublicId',
    Phone: 'Phone',
    City: 'City',
    State: 'State',
    StarId: 'StarId',
    IsActive: 'IsActive',
    IsProspective: 'IsProspective',
    ContactDate: 'ContactDate',
    OrganizationId: 'OrganizationId',
    Xrefs: 'Xrefs',
    AffiliateCodes: 'AffiliateCodes',
    AssignedUserName: 'AssignedUserName',
    BankCode: 'BankCode',
    UserId: 'UserId',
    SourceContactId: 'SourceContactId',
    ParentId: 'ParentId',
    TotalRevenue: 'TotalRevenue',
    GroupId: 'GroupId',
    StreetAddress: 'StreetAddress',
    AffiliateContactName: 'AffiliateContactName',
    AffiliateContactEmailAddress: 'AffiliateContactEmailAddress',
    AffiliateContactAffiliateCodes: 'AffiliateContactAffiliateCodes',
    AffiliateContactId: 'AffiliateContactId',
    AffiliateRate: 'AffiliateRate',
    AffiliateRateTier2: 'AffiliateRateTier2',
    IsSubscribedToEmails: 'IsSubscribedToEmails'
};