export enum AppFeatures {
    Admin = 'Admin',
    API = 'API',
    AppChatFeature = 'App.ChatFeature',
    AppMaxUserCount = 'App.MaxUserCount',
    MaxSpaceGB = 'MaxSpaceGB',
    Notification = 'Notification',
    CRM = 'CRM',
    PFM = 'PFM',
    CFO = 'CFO',
    AdminAdvanced = 'Admin.Advanced',
    AdminCustomizations = 'Admin.Customizations',
    AppChatFeatureTenantToTenant = 'App.ChatFeature.TenantToTenant',
    AppChatFeatureTenantToHost = 'App.ChatFeature.TenantToHost',
    CRMMaxUserCount = 'CRM.MaxUserCount',
    CRMMaxActiveContactCount = 'CRM.MaxActiveContactCount',
    CRMMaxActivePartnerCount = 'CRM.MaxActivePartnerCount',
    CRMBANKCode = 'CRM.BANKCode',
    PFMCreditReport = 'PFM.CreditReport',
    PFMApplications = 'PFM.Applications',
    PFMMaxUserCount = 'PFM.MaxUserCount',
    CFOMaxUserCount = 'CFO.MaxUserCount',
    CFOFutureForecastsYearCount = 'CFO.FutureForecastsYearCount',
    CFOFinancialAccountMaxCount = 'CFO.FinancialAccountMaxCount',
    CFOPartner = 'CFO.Partner',
    CFOMaxUserInstanceCount = 'CFO.MaxUserInstanceCount'
}
