import { KeysEnum } from '@shared/common/keys.enum/keys.enum';
import { LeadDto } from '@app/crm/leads/lead-dto.interface';

export const LeadFields: KeysEnum<LeadDto> = {
    Id: 'Id',
    UserId: 'UserId',
    Name: 'Name',
    CompanyName: 'CompanyName',
    SourceOrganizationUnitId: 'SourceOrganizationUnitId',
    Email: 'Email',
    PhotoPublicId: 'PhotoPublicId',
    Phone: 'Phone',
    City: 'City',
    State: 'State',
    Stage: 'Stage',
    StageId: 'StageId',
    StarId: 'StarId',
    LeadDate: 'LeadDate',
    OrganizationId: 'OrganizationId',
    SourceAffiliateCode: 'SourceAffiliateCode',
    SourceCampaignCode: 'SourceCampaignCode',
    SourceChannelCode: 'SourceChannelCode',
    SourceRefererUrl: 'SourceRefererUrl',
    SourceEntryUrl: 'SourceEntryUrl',
    LastModificationTime: 'LastModificationTime',
    SourceCode: 'SourceCode',
    StreetAddress: 'StreetAddress',
    CustomerId: 'CustomerId',
    ZipCode: 'ZipCode',
    Website: 'Website',
    PhoneExtension: 'PhoneExtension',
    Title: 'Title',
    ContactXref: 'ContactXref',
    ContactAffiliateCode: 'ContactAffiliateCode',
    SourceContactName: 'SourceContactName',
    AssignedUserName: 'AssignedUserName',
    BankCode: 'BankCode',
    StageChecklistPointDoneCount: 'StageChecklistPointDoneCount',
    ContactGroupId: 'ContactGroupId',
    AffiliateContactName: 'AffiliateContactName',
    AffiliateContactAffiliateCode: 'AffiliateContactAffiliateCode',
    PipelineId: 'PipelineId',
    PropertyId: 'PropertyId',
    PropertyName: 'PropertyName',
    Amount: 'Amount'
};