export const defaultCountryZone: {
  [iso: string]: string;
} = {
   "AF":"Afghanistan Standard Time",
   "AL":"Central Europe Standard Time",
   "DZ":"W. Central Africa Standard Time",
   "AS":"UTC-11",
   "AD":"W. Europe Standard Time",
   "AO":"W. Central Africa Standard Time",
   "AI":"SA Western Standard Time",
   "AQ":"Pacific SA Standard Time",
   "AG":"SA Western Standard Time",
   "AR":"Argentina Standard Time",
   "AM":"Caucasus Standard Time",
   "AW":"SA Western Standard Time",
   "AU":"AUS Eastern Standard Time",
   "AT":"W. Europe Standard Time",
   "AZ":"Azerbaijan Standard Time",
   "BS":"Eastern Standard Time",
   "BH":"Arab Standard Time",
   "BD":"Bangladesh Standard Time",
   "BB":"SA Western Standard Time",
   "BY":"Belarus Standard Time",
   "BE":"Romance Standard Time",
   "BZ":"Central America Standard Time",
   "BJ":"W. Central Africa Standard Time",
   "BM":"Atlantic Standard Time",
   "BT":"Bangladesh Standard Time",
   "VE":"Venezuela Standard Time",
   "BO":"SA Western Standard Time",
   "BQ":"SA Western Standard Time",
   "BA":"Central European Standard Time",
   "BW":"South Africa Standard Time",
   "BV":"UTC",
   "BR":"E. South America Standard Time",
   "IO":"Central Asia Standard Time",
   "BN":"Singapore Standard Time",
   "BG":"FLE Standard Time",
   "BF":"Greenwich Standard Time",
   "BI":"South Africa Standard Time",
   "CV":"Cape Verde Standard Time",
   "KH":"SE Asia Standard Time",
   "CM":"W. Central Africa Standard Time",
   "CA":"Eastern Standard Time",
   "KY":"SA Pacific Standard Time",
   "CF":"W. Central Africa Standard Time",
   "TD":"W. Central Africa Standard Time",
   "CL":"Pacific SA Standard Time",
   "CN":"China Standard Time",
   "CX":"SE Asia Standard Time",
   "CC":"Myanmar Standard Time",
   "CO":"SA Pacific Standard Time",
   "KM":"E. Africa Standard Time",
   "CG":"W. Central Africa Standard Time",
   "CD":"W. Central Africa Standard Time",
   "CK":"Hawaiian Standard Time",
   "CR":"Central America Standard Time",
   "HR":"Central European Standard Time",
   "CU":"Eastern Standard Time",
   "CY":"E. Europe Standard Time",
   "CZ":"Central Europe Standard Time",
   "TL":"Tokyo Standard Time",
   "DK":"Romance Standard Time",
   "DJ":"E. Africa Standard Time",
   "DM":"SA Western Standard Time",
   "DO":"SA Western Standard Time",
   "EC":"SA Pacific Standard Time",
   "EG":"Egypt Standard Time",
   "SV":"Central America Standard Time",
   "GQ":"W. Central Africa Standard Time",
   "ER":"E. Africa Standard Time",
   "EE":"FLE Standard Time",
   "ET":"E. Africa Standard Time",
   "FK":"SA Eastern Standard Time",
   "FO":"GMT Standard Time",
   "FJ":"Fiji Standard Time",
   "FI":"FLE Standard Time",
   "FR":"Romance Standard Time",
   "GF":"SA Eastern Standard Time",
   "PF":"Hawaiian Standard Time",
   "TF":"West Asia Standard Time",
   "GA":"W. Central Africa Standard Time",
   "GM":"Greenwich Standard Time",
   "GE":"Georgian Standard Time",
   "DE":"W. Europe Standard Time",
   "GH":"Greenwich Standard Time",
   "GI":"W. Europe Standard Time",
   "GR":"GTB Standard Time",
   "GL":"Greenland Standard Time",
   "GD":"SA Western Standard Time",
   "GP":"SA Western Standard Time",
   "GU":"West Pacific Standard Time",
   "GT":"Central America Standard Time",
   "GG":"GMT Standard Time",
   "GN":"Greenwich Standard Time",
   "GW":"Greenwich Standard Time",
   "GY":"SA Western Standard Time",
   "HT":"Eastern Standard Time",
   "HM":"Mauritius Standard Time",
   "HN":"Central America Standard Time",
   "HK":"China Standard Time",
   "HU":"Central Europe Standard Time",
   "IS":"Greenwich Standard Time",
   "IN":"India Standard Time",
   "ID":"SE Asia Standard Time",
   "IR":"Iran Standard Time",
   "IQ":"Arabic Standard Time",
   "IE":"GMT Standard Time",
   "IL":"Israel Standard Time",
   "IT":"W. Europe Standard Time",
   "JM":"SA Pacific Standard Time",
   "SJ":"W. Europe Standard Time",
   "JP":"Tokyo Standard Time",
   "JE":"GMT Standard Time",
   "JO":"Jordan Standard Time",
   "KZ":"Central Asia Standard Time",
   "KE":"E. Africa Standard Time",
   "KI":"UTC+12",
   "KR":"Korea Standard Time",
   "XK":"Central European Standard Time",
   "KW":"Arab Standard Time",
   "KG":"Central Asia Standard Time",
   "LA":"SE Asia Standard Time",
   "LV":"FLE Standard Time",
   "LB":"Middle East Standard Time",
   "LS":"South Africa Standard Time",
   "LR":"Greenwich Standard Time",
   "LY":"E. Europe Standard Time",
   "LI":"W. Europe Standard Time",
   "LT":"FLE Standard Time",
   "LU":"W. Europe Standard Time",
   "MO":"China Standard Time",
   "MK":"Central European Standard Time",
   "MG":"E. Africa Standard Time",
   "MW":"South Africa Standard Time",
   "MY":"Singapore Standard Time",
   "MV":"West Asia Standard Time",
   "ML":"Greenwich Standard Time",
   "MT":"W. Europe Standard Time",
   "IM":"GMT Standard Time",
   "MH":"UTC+12",
   "MQ":"SA Western Standard Time",
   "MR":"Greenwich Standard Time",
   "MU":"Mauritius Standard Time",
   "YT":"E. Africa Standard Time",
   "MX":"Central Standard Time (Mexico)",
   "FM":"West Pacific Standard Time",
   "MD":"GTB Standard Time",
   "MC":"W. Europe Standard Time",
   "MN":"Ulaanbaatar Standard Time",
   "ME":"Central European Standard Time",
   "MS":"SA Western Standard Time",
   "MA":"Morocco Standard Time",
   "MZ":"South Africa Standard Time",
   "MM":"Myanmar Standard Time",
   "NA":"Namibia Standard Time",
   "NR":"UTC+12",
   "NP":"Nepal Standard Time",
   "NL":"W. Europe Standard Time",
   "NC":"Central Pacific Standard Time",
   "NZ":"New Zealand Standard Time",
   "NI":"Central America Standard Time",
   "NE":"W. Central Africa Standard Time",
   "NG":"W. Central Africa Standard Time",
   "NU":"UTC-11",
   "NF":"Central Pacific Standard Time",
   "KP":"Korea Standard Time",
   "MP":"West Pacific Standard Time",
   "NO":"W. Europe Standard Time",
   "OM":"Arabian Standard Time",
   "PK":"Pakistan Standard Time",
   "PW":"Tokyo Standard Time",
   "PS":"Egypt Standard Time",
   "PA":"SA Pacific Standard Time",
   "PG":"West Pacific Standard Time",
   "PY":"Paraguay Standard Time",
   "PE":"SA Pacific Standard Time",
   "PH":"Singapore Standard Time",
   "PN":"Pacific Standard Time",
   "PL":"Central European Standard Time",
   "PT":"GMT Standard Time",
   "PR":"SA Western Standard Time",
   "QA":"Arab Standard Time",
   "RE":"Mauritius Standard Time",
   "RO":"GTB Standard Time",
   "RU":"Russian Standard Time",
   "RW":"South Africa Standard Time",
   "SH":"Greenwich Standard Time",
   "KN":"SA Western Standard Time",
   "LC":"SA Western Standard Time",
   "MF":"SA Western Standard Time",
   "PM":"Greenland Standard Time",
   "VC":"SA Western Standard Time",
   "WS":"Samoa Standard Time",
   "SM":"W. Europe Standard Time",
   "SA":"Arab Standard Time",
   "SN":"Greenwich Standard Time",
   "RS":"Central Europe Standard Time",
   "SC":"Mauritius Standard Time",
   "SL":"Greenwich Standard Time",
   "SG":"Singapore Standard Time",
   "SX":"SA Western Standard Time",
   "SK":"Central Europe Standard Time",
   "SI":"Central Europe Standard Time",
   "SB":"Central Pacific Standard Time",
   "SO":"E. Africa Standard Time",
   "ZA":"South Africa Standard Time",
   "GS":"UTC-02",
   "SS":"E. Africa Standard Time",
   "ES":"Romance Standard Time",
   "LK":"Sri Lanka Standard Time",
   "SD":"E. Africa Standard Time",
   "SR":"SA Eastern Standard Time",
   "SZ":"South Africa Standard Time",
   "SE":"W. Europe Standard Time",
   "CH":"W. Europe Standard Time",
   "SY":"Syria Standard Time",
   "TW":"Taipei Standard Time",
   "TJ":"West Asia Standard Time",
   "TZ":"E. Africa Standard Time",
   "TH":"SE Asia Standard Time",
   "TG":"Greenwich Standard Time",
   "TK":"Tonga Standard Time",
   "TO":"Tonga Standard Time",
   "TT":"SA Western Standard Time",
   "TN":"W. Central Africa Standard Time",
   "TR":"Turkey Standard Time",
   "TM":"West Asia Standard Time",
   "TC":"Eastern Standard Time",
   "TV":"UTC+12",
   "UM":"UTC-11",
   "UG":"E. Africa Standard Time",
   "UA":"FLE Standard Time",
   "AE":"Arabian Standard Time",
   "GB":"GMT Standard Time",
   "US":"Mountain Standard Time",
   "UY":"Montevideo Standard Time",
   "UZ":"West Asia Standard Time",
   "VU":"Central Pacific Standard Time",
   "VA":"W. Europe Standard Time",
   "VN":"SE Asia Standard Time",
   "VI":"SA Western Standard Time",
   "VG":"SA Western Standard Time",
   "WF":"UTC+12",
   "YE":"Arab Standard Time",
   "ZM":"South Africa Standard Time",
   "ZW":"South Africa Standard Time"
};