import { KeysEnum } from '@shared/common/keys.enum/keys.enum';
import { CommissionDto } from '@app/crm/commission-history/commission-dto';

export const CommissionFields: KeysEnum<CommissionDto> = {
    BuyerAffiliateContactId: 'BuyerAffiliateContactId',
    BuyerAffiliateName: 'BuyerAffiliateName',
    BuyerAffiliateCode: 'BuyerAffiliateCode',
    BuyerContactId: 'BuyerContactId',
    BuyerEmailAddress: 'BuyerEmailAddress',
    BuyerName: 'BuyerName',
    Tier: 'Tier',
    CommissionAmount: 'CommissionAmount',
    CommissionRate: 'CommissionRate',
    CommissionableAmount: 'CommissionableAmount',
    CurrencyId: 'CurrencyId',
    EarnedDate: 'EarnedDate',
    Id: 'Id',
    InvoiceDate: 'InvoiceDate',
    InvoiceNumber: 'InvoiceNumber',
    InvoiceStatus: 'InvoiceStatus',
    OrderDate: 'OrderDate',
    OrderNumber: 'OrderNumber',
    ProductAmount: 'ProductAmount',
    ProductCode: 'ProductCode',
    ProductName: 'ProductName',
    ResellerAffiliateRate: 'ResellerAffiliateRate',
    ResellerAffiliateCode: 'ResellerAffiliateCode',
    ResellerContactId: 'ResellerContactId',
    ResellerEmailAddress: 'ResellerEmailAddress',
    ResellerName: 'ResellerName',
    Status: 'Status',
    TransactionAuthCode: 'TransactionAuthCode',
    TransactionDate: 'TransactionDate',
    TransactionGatewayName: 'TransactionGatewayName',
    TransactionId: 'TransactionId',
    OrderId: 'OrderId'
};